<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * achatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class achatRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAchatPourRenouvellement(){
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.renouvellement is null')
		   ->andWhere('a.facture is not null');
		return $qb->getQuery()
				  ->getResult();   	
	}

 public function rechercherAchats($criteres)
    {
       
        $where  = "";
        foreach ($criteres as $key => $value) {
            $where .= " and ".$value;
        }
        $query = 'SELECT a  FROM gestionachatsFondDeRoulementBundle:Achat a ';       
       
        
        $query .= ' WHERE 1=1 '.$where;

        $qb = $this->getEntityManager()
                   ->createQuery($query); 
                   
        return $qb->getResult(); 
           
    }
    



}
