<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * DemandeHasEtatDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeHasEtatDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
