<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * Etat_renouvellementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etat_renouvellementRepository extends \Doctrine\ORM\EntityRepository
{
}
