<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * EtatRenouvellementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatRenouvellementRepository extends \Doctrine\ORM\EntityRepository
{
}
