<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * EtatDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
