<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * LigneDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
