<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * RenouvellementHasEtatRenouvellementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RenouvellementHasEtatRenouvellementRepository extends \Doctrine\ORM\EntityRepository
{
}
