<?php

namespace gestion\achatsFondDeRoulementBundle\Repository;

/**
 * UniterattacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniterattacheRepository extends \Doctrine\ORM\EntityRepository
{
}
