# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    service.custom:
       class: gestion\achatsFondDeRoulementBundle\Services\CustomService
       arguments: ["@doctrine.orm.entity_manager"] 

    app.form.registration:
        class: administrationBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }   
            
    admin.access:
        class: administrationBundle\Services\AccessService
        arguments: ["@doctrine.orm.entity_manager"]     