<?php

namespace administrationBundle\Repository;

/**
 * FonctionnaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionnaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
