<?php

namespace administrationBundle\Repository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{

	public function findFonctionnaliesByProfil($profil_id,$fonctionnalite_id)
    {

    	$qb = $this->createQueryBuilder("p")
    	->innerJoin('p.fonctionnalites', 'f')
	    ->where('f.id = :fonctionnalite_id')
	    ->setParameter('fonctionnalite_id', $fonctionnalite_id)
	    ->andWhere('p.id = :profil_id')
	    ->setParameter('profil_id', $profil_id);

    	return $qb->getQuery()->getResult();
    }

}
